In [9]:
import numpy as np
x=np.array([1,2,3,5])
n=6
np.column_stack([x**(n-1-i) for i in range(n)])

array([[   1,    1,    1,    1,    1,    1],
       [  32,   16,    8,    4,    2,    1],
       [ 243,   81,   27,    9,    3,    1],
       [3125,  625,  125,   25,    5,    1]], dtype=int32)

In [13]:
#Task 1
#1.Write a function to compute 5/0 and use try/except to catch the exceptions. 
def divide(num1,num2):
    return num1/num2
try:
    print("the result of 5 divided by zero",divide(5,0))
except:
    print("zero division error")

    

zero division error


In [36]:
#Task 1
#2.Python program to generate all sentences
subjects=["Americans ","Indians "]
verbs=["play ","watch "]
objects=["Baseball ","Cricket "] 
for subject in subjects:
    for verb in verbs:
        for object1 in objects:
            print (subject+verb+object1)

Americans play Baseball 
Americans play Cricket 
Americans watch Baseball 
Americans watch Cricket 
Indians play Baseball 
Indians play Cricket 
Indians watch Baseball 
Indians watch Cricket 


In [39]:
#Task 2
#Write a function so that the columns of the output matrix are powers of the input vector.  
#The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.
import numpy as np
x=np.array([1,2,3,5])
n=4
matrix = np.column_stack([x**(n-1-i) for i in range(n)])
print(matrix)

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
